### ISSUE TITLE
css三角形 平行四边形

### ISSUE THREAD

**Issue by Lpmvb** [Lpmvb/Jingwei#5]
## 三角形
```html
<div class="triangle"></div>
```
```less
.triangle {
  width: 20px;
  height: 20px;
  display: inline-block;
  border-color: red green yellow black;
  border-width: 20px 20px 20px 20px;
  border-style: solid;
}
```
![image](https://user-images.githubusercontent.com/34727913/35614547-6c5ef888-06aa-11e8-84fa-ff45d227f150.png)

修改宽度
```less
.triangle {
  border-width: 0px 20px 40px 20px;
}
```
![image](https://user-images.githubusercontent.com/34727913/35614647-c7ea5986-06aa-11e8-983c-96960fcd9024.png)

修改颜色
```less
.triangle {
  border-color: red transparent yellow transparent;
}
```
![image](https://user-images.githubusercontent.com/34727913/35614710-f717af1a-06aa-11e8-9cd9-35e1222410d4.png)

## 平行四边形
```less
{
  width: 40px;
  height: 40px;
  display: inline-block;
  position: relative;
  &::after {
    content: '';
    position: absolute;
    right: -20px;
    border-color: red transparent yellow black;
    border-width: 40px 20px 0px 20px;
    border-style: solid;
  }
  &::before {
    content: '';
    position: absolute;
    left: -20px;
    border-color: red green yellow transparent;
    border-width: 0px 20px 40px 20px;
    border-style: solid;
  }
}
```
![image](https://user-images.githubusercontent.com/34727913/35615699-e283d2ce-06ad-11e8-9747-94b805c6cb1f.png)
